base_url: "https://flagship-sqa-test.flexgalaxy.com"
result: "sucess"
site1:
  name: sqa-test  # 备注,不会显示才对.
  id: 02
  user: # 这是一个列表.user:[1,2,'3,4'] 只有3个元素.
    - 1  # 这三个数是同级元素
    - 2
    - 3,4
site2:
  name: sqa-spare-test
  id: 1001
