招商白酒C:
  - code: '012414'
  - money: 0
国联安半导体:
  - code: '007301'
  - money: 54448
银河创新成长C:
  - code: '014143'
  - money: 52440
广发医疗C:
  - code: '009163'
  - money: 0
工银新能源汽车C:
  - code: '005940'
  - money: 21289
诺安半导体:
  - code: '320007'
  - money: 12300
农银新能源:
  - code: '000336'
  - money: 8965
华夏新能源A:
  - code: '003834'
  - money: 9212
华夏半导体:
  - code: '008888'
  - money: 3923
国泰新能源车:
  - code: '009068'
  - money: 4564
嘉实光伏C:
  - code: '014605'
  - money: 0
招商生物C:
  - code: '012417'
  - money: 0