picking_err: Ture  # 拣货是否进行异常上报.
bind_err: True  # 绑定载物箱时上报找不到载物箱.
err_code: True  # 输入错误的商品码.
more_good: True # 输入更多的商品数值.
pasue_move: False # 是否暂停移动.
pick_psb: 15  # 拣货上报异常的概率.
more_psb: 15  # 多输入几个商品数量的概率.
err_code_psb: 15 # 输入错误商品码的概率.1/15


