# SpeedPicker运行的配置文件,从这里面修改,尽量不要动脚本了.
picking_err: Ture  # 拣货是否进行异常上报.
bind_err: True  # 绑定载物箱时上报找不到载物箱.
err_code: True  # 输入错误的商品码.
more_good: True # 输入更多的商品数值.
pasue_move: False # 是否暂停移动.
pasue_psb: 2  # 暂停移动的概率 1/2
pick_psb: 15  # 拣货上报异常的概率.1/15
more_psb: 15  # 多输入几个商品数量的概率.1/15
err_code_psb: 15 # 输入错误商品码的概率.1/15
sp_text:
  - 等待任务中
  - 紧急拣货中
  - 前往
  - 拣货异常
  - 拣货中
  - 异常上报
  - 输入
  - 暂停
  - 恢复
  - 拣货执行结果
  - 隔口名称
  - 任务被终止
  - 请取下载物箱或货品
  - 已取下
bind_text: # 绑定载物箱界面的文本
  - 扫码绑定 载物箱
  - 扫码绑定载物箱
  - 请放置好载物箱，并归位扫码枪
api_order: True
order_site: "202"


