# SpeedPicker运行的配置文件,从这里面修改,尽量不要动脚本了.
picking_err: Ture  # 拣货是否进行异常上报.
bind_err: True  # 绑定载物箱时上报找不到载物箱.
err_code: True  # 输入错误的商品码.
more_good: True # 输入更多的商品数值.
pasue_move: True # 是否暂停移动.
pasue_psb: 2  # 暂停移动的概率 1/2
pick_psb: 15  # 拣货上报异常的概率.1/15
more_psb: 15  # 多输入几个商品数量的概率.1/15
err_code_psb: 15 # 输入错误商品码的概率.1/15
sp_text:
  - 等待任务中
  - 紧急拣货中
  - 前往
  - 拣货异常
  - 拣货中
  - 异常上报
  - 输入
  - 暂停
  - 恢复
  - 拣货执行结果
  - 隔口名称
  - 任务被终止
  - 请取下载物箱或货品
  - 已取下
bind_text: # 绑定载物箱界面的文本
  - 扫码绑定 载物箱
  - 扫码绑定载物箱
  - 请放置好载物箱，并归位扫码枪
container_code:
  1A_container: 1647845001926471   # 特定的载物箱码.
  3A_container: 3A_con@02
  6A_container: 6A_con-@1
  9A_container: 19910318151 6ccc!@#$
api_order: True
order_site: "202"
estop_text:
  - 紧急停止
  - 若需恢复工作
  - 请解除急停状态

confirm_result:
  - 载物箱编码：
  - 拣货执行结果
  - 格口名称
  - 单据
picking_out: 10 # 拣货超时几率 1/10, 1是常开,0是常闭.
picking_outtime: 20  # 拣货超时时间 30s
wait_finshed: 15  # 等待点击超时按钮的超时时间,30s
exit_ggr:
  - '第 1 屏，共 2 屏'
  - '天气小工具'
  - '华为视频'
  - '音乐'
  - '平板管家'
  - '浏览器'
  - '图库'
  - '页面指示器'
  - 'Dock 区应用'
  - '页面指示器'
  - '文件夹 实用工具'
err_text: # 拣货异常时,页面的特殊文本
  - 货品缺货需人工拣取
  - 其他需人工拣取
  - 拣货异常