inputbtn: (By.XPATH, '//input[@name="wd"]')
searchbtn: (By.XPATH, '//input[@value="百度一下"]')
1126: 1
  - 致命1
1144: 10
  - 致命2
  - 严重8
1160: 11
  - 严重8
  - 一般3
1189: 29
  - 致命5
  - 严重13
  - 一般10
  - 提示1
1221: 15
  - 致命 2
  - 严重 7
  - 一般 6
1236: 17
  - 致命5
  - 严重8
  - 一般4