# 这是一个yaml文件示例文档.
text1: 字符串  # 直接写,是字符串,但是数字的话,直接是整型.
person: # person:[{"name":"张三"},{"age":18}]
  - name: 张三
  - age: 18  # 数字的整型
  - gender: 男
  - hobit: [ '喝酒','抽烟','打游戏' ]  # 这里能得到一个列表.{'hobit': ['喝酒', '抽烟', '打游戏']}
set1: { 'A','B','C' }  # 并不能直接得到一个集合,因为已经红框标注了.'set1': {'A': None, 'B': None, 'C': None}
set2: !!set { 'A','B','C' }  # 这样就能得到集合类型了. 'set2': {'C', 'B', 'A'}}
---   # 多文本了,读取方式要变,不然只能读取到这个上面的信息.
set3: 1
---
data5: 2
1: 2