# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import Demo_pb2 as Demo__pb2


class DemoTestStub(object):
    """关键字 + 服务名称 空格 大括号
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.DemoReq = channel.unary_unary(
                '/test.DemoTest/DemoReq',
                request_serializer=Demo__pb2.OneRequest.SerializeToString,
                response_deserializer=Demo__pb2.OneResponse.FromString,
                )


class DemoTestServicer(object):
    """关键字 + 服务名称 空格 大括号
    """

    def DemoReq(self, request, context):
        """请求和请求对象可以不同名。 returns 后面直接括号说明返回。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DemoTestServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'DemoReq': grpc.unary_unary_rpc_method_handler(
                    servicer.DemoReq,
                    request_deserializer=Demo__pb2.OneRequest.FromString,
                    response_serializer=Demo__pb2.OneResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'test.DemoTest', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DemoTest(object):
    """关键字 + 服务名称 空格 大括号
    """

    @staticmethod
    def DemoReq(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/test.DemoTest/DemoReq',
            Demo__pb2.OneRequest.SerializeToString,
            Demo__pb2.OneResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
