# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Demo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nDemo.proto\x12\x04test\"\'\n\nOneRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x03\"\x1d\n\x0bOneResponse\x12\x0e\n\x06result\x18\x01 \x01(\t2<\n\x08\x44\x65moTest\x12\x30\n\x07\x44\x65moReq\x12\x10.test.OneRequest\x1a\x11.test.OneResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'Demo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _ONEREQUEST._serialized_start=20
  _ONEREQUEST._serialized_end=59
  _ONERESPONSE._serialized_start=61
  _ONERESPONSE._serialized_end=90
  _DEMOTEST._serialized_start=92
  _DEMOTEST._serialized_end=152
# @@protoc_insertion_point(module_scope)
