# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\x12\x04test\")\n\x0cHelloWordReq\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\"\x1e\n\x0cHelloWordRes\x12\x0e\n\x06result\x18\x01 \x01(\t2=\n\x04\x44\x65mo\x12\x35\n\tHelloWord\x12\x12.test.HelloWordReq\x1a\x12.test.HelloWordRes\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLOWORDREQ._serialized_start=20
  _HELLOWORDREQ._serialized_end=61
  _HELLOWORDRES._serialized_start=63
  _HELLOWORDRES._serialized_end=93
  _DEMO._serialized_start=95
  _DEMO._serialized_end=156
# @@protoc_insertion_point(module_scope)
