# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import hello_bilibili_pb2 as hello__bilibili__pb2


class BibiliStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.HelloDewei = channel.unary_unary(
                '/test.Bibili/HelloDewei',
                request_serializer=hello__bilibili__pb2.HelloDeweiReq.SerializeToString,
                response_deserializer=hello__bilibili__pb2.HelloDeweiReply.FromString,
                )


class BibiliServicer(object):
    """Missing associated documentation comment in .proto file."""

    def HelloDewei(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BibiliServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'HelloDewei': grpc.unary_unary_rpc_method_handler(
                    servicer.HelloDewei,
                    request_deserializer=hello__bilibili__pb2.HelloDeweiReq.FromString,
                    response_serializer=hello__bilibili__pb2.HelloDeweiReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'test.Bibili', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Bibili(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def HelloDewei(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/test.Bibili/HelloDewei',
            hello__bilibili__pb2.HelloDeweiReq.SerializeToString,
            hello__bilibili__pb2.HelloDeweiReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
