# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello_bilibili.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14hello_bilibili.proto\x12\x04test\"*\n\rHelloDeweiReq\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0b\n\x03\x61ge\x18\x02 \x01(\x05\"!\n\x0fHelloDeweiReply\x12\x0e\n\x06result\x18\x01 \x01(\t2D\n\x06\x42ibili\x12:\n\nHelloDewei\x12\x13.test.HelloDeweiReq\x1a\x15.test.HelloDeweiReply\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'hello_bilibili_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _HELLODEWEIREQ._serialized_start=30
  _HELLODEWEIREQ._serialized_end=72
  _HELLODEWEIREPLY._serialized_start=74
  _HELLODEWEIREPLY._serialized_end=107
  _BIBILI._serialized_start=109
  _BIBILI._serialized_end=177
# @@protoc_insertion_point(module_scope)
